---
- name: Install statsd
  pip:
    name: "{{ item }}"
    virtualenv: /root/satellite_venv
  with_items:
    - statsd
    - psycopg2

- name: Install the required packages to run stats collection
  pip:
    name: statsd-plugin
    virtualenv: /root/satellite_venv

- name: Get Candlepin PostgresDB Password
  command: grep "jpa.config.hibernate.connection.password" /etc/candlepin/candlepin.conf
  register: satellite_candlepin_password

- name: Get Foreman PostgresDB Password
  shell: grep "password" /etc/foreman/database.yml | awk '{print $2}' | tr -d '"'
  register: foreman_password

- name: Deploy statistics collection service
  template:
    src: satellite_stats.py.j2
    dest: /usr/bin/satellite_stats.py

- name: Deploy SystemD service
  copy:
    src: satellite-reporter.service
    dest: /usr/lib/systemd/system/satellite-reporter.service

- name: Confirm if collectd is running
  service:
    name: collectd
    state: running
    enabled: yes

- name: Start the Satellite monitoring service
  service:
    name: satellite-reporter
    state: started
    enabled: yes
